import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { NextAuthProvider } from './Providers'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BlogApp | SURAJ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Navbar/>
          <div className='lg:max-w-[1000px] lg:px-16 mx-auto py-8 shadow-2xl min-h-screen flex flex-col flex-auto px-10'>
            {children}
          </div>
          <Footer/>
          <Toaster/>
        </NextAuthProvider>
      </body>
    </html>
  )
}
